require('core.basic')
require('core.functions')
require('keymaps.editor.editor_keymap')
require('keymaps.plugin.plugin-keymap')
require('plugin.lazynvim')
require('plugin.plugin-list')
require('plugin.mason-lspconfig')
require('core.theme')